# docker-compose version
version: '3.9'

# All the containers to run.
services:
  api:
    build:
      context: './services/api'
      dockerfile: 'Dockerfile'

    container_name: 'api'

    ports:
      - '${PUSH_NOTIFICATIONS_API_PORT:-}:80'

    env:
      - 'VAPID__EMAIL_ADDRESS=${VAPID__EMAIL_ADDRESS:-}'

    restart: 'always'

  app:
    build:
      context: '.'
      dockerfile: './services/app/Dockerfile'

    container_name: 'app'

    ports:
      - '${PUSH_NOTIFICATIONS_APP_PORT:-}:3000'

    restart: 'always'

# Ensure all the services in this docker-compose file connect to the tix-factory docker network.
networks:
  default:
    name: 'tix-factory'
    external: true
