# https://docs.digitalocean.com/glossary/app-spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# The app spec, is a YAML manifest that declaratively states everything about your app.
# Including each resource and all of your app’s environment variables and configuration variables.
name: 'push-notifications-demo'

# The domain names where the app is accessible on the public internet.
domains:
  - domain: 'demo.push-notifications.app'
    type: 'PRIMARY'

services:
  # This is the backend for the push notifications demo,
  # the thing actually sending the push notifications.
  - name: 'push-notifications-api'
    github:
      branch: 'main'
      deploy_on_push: true
      repo: 'tix-factory/push-notifications-demo'
    health_check:
      http_path: '/health'
    http_port: 80
    instance_count: 1
    instance_size_slug: 'basic-xxs'
    routes:
      - path: /api
        preserve_path_prefix: true
    source_dir: 'services/api'
    dockerfile_path: 'services/api/Dockerfile'

static_sites:
  # This is the app that the humans interact with in their web browsers.
  - name: 'push-notifications-app'
    github:
      branch: 'main'
      deploy_on_push: true
      repo: 'tix-factory/push-notifications-demo'
    source_dir: 'services/app'
    output_dir: 'build'
    build_command: 'npm run build'
    environment_slug: 'node-js'
