name: 'push-notifications-demo'

on:
  # Ensure the build runs on pull requests.
  pull_request:

  # Ensure the build runs when pushed to the main branch.
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    env:
      PUSH_NOTIFICATIONS_APP_PORT: 3000
      PUSH_NOTIFICATIONS_API_PORT: 5000

    steps:
      - name: '📥 Clone Repository'
        uses: actions/checkout@v7

      - name: '🌐 Setup Network'
        run: >-
          docker network create tix-factory
        continue-on-error: true

      - name: '🏗️ Build'
        run: >-
          docker compose build

      - name: '🐳 Run'
        run: |
          docker compose up -d
          sleep 5
        env:
          VAPID__EMAIL_ADDRESS: 'example@example.com'

      - name: '🔌 Ensure Connectivity (api)'
        run: >-
          curl -v --fail http://localhost:${{ env.PUSH_NOTIFICATIONS_API_PORT }}/api/v1/push-notifications/metadata

      - name: '🔌 Ensure Connectivity (app)'
        run: >-
          curl -v --fail http://localhost:${{ env.PUSH_NOTIFICATIONS_APP_PORT }}

      - name: '🪵 Logs (api)'
        if: ${{ always() }}
        run: >-
          docker compose logs api

      - name: '🪵 Logs (app)'
        if: ${{ always() }}
        run: >-
          docker compose logs app

      - name: '🛑 Stop Containers'
        run: >-
          docker compose rm
          --stop
          --force

  deploy:
    runs-on: 'ubuntu-latest'

    environment: ${{ github.event_name == 'push' && 'release' || '' }}

    steps:
      - name: '📥 Clone Repository'
        uses: actions/checkout@v7

      - name: '🟩 Setup node'
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: '🧶 npm ci'
        run: |-
          npm ci
        working-directory: services/app

      - name: '🏗️ Build (app)'
        run: |-
          npm run ci
        working-directory: services/app

      - name: '🚅 Deploy'
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: >-
            ${{ github.event_name == 'push' && 'deploy' || 'deploy --dry-run' }}
            --message "Deployed by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          workingDirectory: 'services/app'
