name: '@tix-factory/push-notifications'

on:
  # Ensure the build runs on pull requests.
  pull_request:
    paths:
      - '.github/workflows/push-notifications-npm.yml'
      - 'libs/js/push-notifications/**'

  # Ensure the build runs when pushed to the main branch.
  push:
    branches:
      - main

    paths:
      - '.github/workflows/push-notifications-npm.yml'
      - 'libs/js/push-notifications/**'

# Cancel any workflow that's running if we make another commit on the same pull request.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    environment: ${{ github.event_name == 'push' && 'release' || '' }}

    permissions:
      contents: read

      # Used for npm authentication
      id-token: write

    steps:
      # Setup
      - name: '📥 Clone Repository'
        uses: actions/checkout@v7

      - name: '🟩 Setup Node'
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      # Build
      - name: '📜 Copy License'
        run: |
          cp LICENSE ./libs/js/push-notifications

      - name: '🚚 Install Packages'
        run: |
          npm ci
        working-directory: libs/js/push-notifications

      - name: '🏗️ Build'
        run: |
          npm run build
        working-directory: libs/js/push-notifications

      # Publish
      - name: '📤 Upload to npm'
        run: >-
          npm publish
          --access public
          ${{ github.event_name == 'pull_request' && '--dry-run' || '' }}
        working-directory: libs/js/push-notifications
